---
title: "R Packages"
author: "PPOL 670"
date: "11/29/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = F)
```

## `datapasta`
```{r}
install.packages('datapasta')
library(datapasta)


## Example table
## https://docs.google.com/spreadsheets/d/1XTMcmuu0agQVC7IDN8UQvw1KfDPI_MMuY9vmFCyoOTg/edit?usp=sharing






```

## `googlesheets4`
```{r}
install.packages('googlesheets4')
library(googlesheets4)

#Authenticate
gs4_auth()

#Read
example <- read_sheet(ss = '1XTMcmuu0agQVC7IDN8UQvw1KfDPI_MMuY9vmFCyoOTg', 
           sheet = 1)

#Write
cc_tweets <- read.csv('https://raw.githubusercontent.com/apodkul/ppol670_01/main/Labs/Week11/Climate_tweets.csv')

write_sheet(ss = '1XTMcmuu0agQVC7IDN8UQvw1KfDPI_MMuY9vmFCyoOTg', 
            data = cc_tweets,
            sheet = 'ClimateTweets')

```

## `data.table`
```{r}
install.packages('data.table')
library(data.table)

cc_tweets <- fread('https://raw.githubusercontent.com/apodkul/ppol670_01/main/Labs/Week11/Climate_tweets.csv')

cc_tweets <- fread('https://raw.githubusercontent.com/apodkul/ppol670_01/main/Labs/Week11/Climate_tweets.csv', 
                   sep = 'auto')

```

## `plotly`
```{r}
install.packages('plotly')
library(plotly)
library(ggplot2)

admit <- read.csv('https://raw.githubusercontent.com/apodkul/ppol670_01/main/Labs/Week12/Admissions_missing.csv')

ggplot(admit, aes(x = GRE.Score, y = Chance.of.Admit)) + 
  geom_point()

p1 <- ggplot(admit, aes(x = GRE.Score, y = Chance.of.Admit)) + 
  geom_point() 

ggplotly(p1)

p2 <- ggplot(admit, aes(x = GRE.Score, 
                        y = Chance.of.Admit, 
                        text = paste0("SOP: ", SOP, '\n',
                                      "CGPA: ", CGPA))) + 
  geom_point() 

ggplotly(p2, tooltip = 'text')
  
```

## `kableExtra`
```{r}
install.packages('kableExtra')
library(kableExtra)
library(dplyr)

admit %>% 
  group_by(Research) %>%
  summarize(Admit_Chance = median(Chance.of.Admit, na.rm = T)) %>%
  kbl()
```

## `cronR`
```{r}
install.packages('cronR')
library(cronR)

cron_ls()

cron_add(...)
```

## `inspectdf`
```{r}
install.packages('inspectdf')
library(inspectdf)

admit %>% 
  inspect_na()

admit %>% 
  inspect_num()
```

## Installing via `devtools`
```{r}
install.packages('devtools')
library(devtools)
#https://github.com/hadley/emo

install_github('hadley/emo')
ji('face')
```

## `RSelenium`
```{r}
install.packages('RSelenium')
library(RSelenium)

#Start Browser 
browser_x <- rsDriver(browser = 'firefox', 
                      port = 4544L, 
                      verbose = T)
browser_drive <- browser_x[['client']]

browser_drive$navigate(
  "https://www.politico.com"
  )

input <- 'Georgetown University'
field <- browser_drive$findElement(
  using = 'css', 
  value = '#searchInput'
  )
field$sendKeysToElement(list(input))

button <- browser_drive$findElement(
  using = 'css', 
  value = '.pure-button-primary-progressive'
  )
button$clickElement()

html <- browser_drive$getPageSource()[[1]]

x <- html %>% 
  read_html() %>%
  html_elements('h3')

```
